glyphrepository/glyph/models.py
# -*- coding: utf-8 -*-
"""Glyph models."""
from __future__ import division

from glyphrepository.database import Column, Model, SurrogatePK, db, reference_col, relationship

from flask import current_app as app
import os

class Glyph(SurrogatePK, Model):
    """A glyph."""

    __tablename__ = 'glyphs'
    name = Column(db.String(80), unique=False, nullable=False)
    file_name = Column(db.String(80), unique=False, nullable=False)

    has_pdf = Column(db.Boolean)
    has_png = Column(db.Boolean)
    has_svg = Column(db.Boolean)
    has_jpg = Column(db.Boolean)

    has_specification_pdf = Column(db.Boolean)
    has_specification_png = Column(db.Boolean)
    has_specification_svg = Column(db.Boolean)
    has_specification_jpg = Column(db.Boolean)

    sbol_status = Column(db.String(80), unique=False, nullable=True)
    proposal_url = Column(db.String(80), unique=False, nullable=True)

    soterm_id = reference_col('soterms', nullable=True)
    soterm = relationship('SOterm', backref='glyphs')

    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='glyphs')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)

    def average_rating(self):
        """Return the average rating for a glyph, rounded to one decimal place"""

        # Make a list of all ratings >= 0 (-1 is a sentinel value for unrated)
        # avoid multiply counting ratings from the same user
        users = []
        ratings = []
        for comment in self.comments:
            if comment.rating >= 0 and comment.user_id not in users:
                ratings.append(comment.rating)
                users.append(comment.user_id)

        if len(ratings) == 0:
            return ""
        else:
            return "%.1f" % (sum(ratings) / len(ratings))

    def get_soterm_link(self):
        if self.soterm:
            full_id = self.soterm.get_full_id()
            return '<a href="/soterm/%s"> %s (%s)</a>' % (full_id, self.soterm.name, full_id)
        else:
            return ""

    @staticmethod
    def allowed_file(filename):
        return '.' in filename and \
               filename.rsplit('.', 1)[1].lower() in set(['pdf', 'png', 'jpg', 'jpeg', 'svg'])

    def save_glyph_file(self, f):
        file_name = f.filename

        if Glyph.allowed_file(file_name):
            UPLOAD_FOLDER = os.path.join(app.root_path, 'static/glyphs')
            file_extension = os.path.splitext(file_name)[-1].lower().replace('jpeg', 'jpg')
            filename = str(self.id) + file_extension

            f.save(os.path.join(UPLOAD_FOLDER, filename))
            self.record_file(file_extension)
            return True

    def save_specification_file(self, f):
        file_name = f.filename

        if Glyph.allowed_file(file_name):
            UPLOAD_FOLDER = os.path.join(app.root_path, 'static/glyphs')
            file_extension = os.path.splitext(file_name)[-1].lower().replace('jpeg', 'jpg')
            filename = str(self.id) + "_specification" + file_extension

            f.save(os.path.join(UPLOAD_FOLDER, filename))
            self.record_spec_file(file_extension)

    def record_file(self, file_extension):
        if file_extension[0] == ".":
            file_extension = file_extension[1:]

        if file_extension == "pdf":
            self.has_pdf = True
        elif file_extension == "png":
            self.has_png = True
        elif file_extension == "svg":
            self.has_svg = True
        elif file_extension == "jpg":
            self.has_jpg = True

        self.save()

    def record_spec_file(self, file_extension):
        if file_extension[0] == ".":
            file_extension = file_extension[1:]

        if file_extension == "pdf":
            self.has_specification_pdf = True
        elif file_extension == "png":
            self.has_specification_png = True
        elif file_extension == "svg":
            self.has_specification_svg = True
        elif file_extension == "jpg":
            self.has_specification_jpg = True

        self.save()

    def get_preferred_filename(self):
        if self.has_png:
            return str(self.id) + ".png"
        elif self.has_svg:
            return str(self.id) + ".svg"
        elif self.has_jpg:
            return str(self.id) + ".jpg"
        elif self.has_pdf:
            return str(self.id) + ".pdf"
        else:
            return ""

    def get_preferred_specification_filename(self):
        if self.has_specification_png:
            return str(self.id) + "_specification.png"
        elif self.has_specification_svg:
            return str(self.id) + "_specification.svg"
        elif self.has_specification_jpg:
            return str(self.id) + "_specification.jpg"
        elif self.has_specification_pdf:
            return str(self.id) + "_specification.pdf"
        else:
            return ""

glyphrepository/glyph/forms.py
# -*- coding: utf-8 -*-
"""Glyph forms."""
from flask_wtf import Form
from wtforms import StringField, FileField, SelectField
from wtforms.validators import DataRequired


class AddGlyphForm(Form):
    """Form to add a new glyph."""

    name = StringField('Glyph name', validators=[DataRequired()])
    soTerm = SelectField('SO term', choices=[])
    sbol_status = SelectField('Status in SBOLv standard process',
                              choices=map(lambda x: (x, x),['Proposed', 'Endorsed', 'Adopted (recommended)', 'Adopted (alternative)']))
    proposal_url = StringField('URL of proposal google doc')

    file_path1 = FileField(label="Image")
    file_path2 = FileField(label="Image")
    file_path3 = FileField(label="Image")
    file_path4 = FileField(label="Image")

    file_spec_path1 = FileField(label="Image")
    file_spec_path2 = FileField(label="Image")
    file_spec_path3 = FileField(label="Image")
    file_spec_path4 = FileField(label="Image")

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddGlyphForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        return super(AddGlyphForm, self).validate()

glyphrepository/glyph/__init__.py
# -*- coding: utf-8 -*-
"""The glyph module."""
from . import views  # noqa

glyphrepository/glyph/views.py
# -*- coding: utf-8 -*-
"""Section for viewing/editing a part."""
from flask import Blueprint, redirect, render_template, url_for, request, flash
from glyphrepository.utils import flash_errors

from glyphrepository.glyph.models import Glyph
from glyphrepository.comment.models import Comment

from glyphrepository.glyph.forms import AddGlyphForm
from glyphrepository.comment.forms import CommentForm
from glyphrepository.soterm.models import SOterm
from flask_login import login_required, current_user

blueprint = Blueprint('glyph', __name__, static_folder='../static', url_prefix='/glyph',)


@blueprint.route('/', methods=['GET', 'POST'])
def home():
    """ If no part id specified, redirect home """
    return redirect(url_for('public.home'))

@blueprint.route('/<glyph_id>', methods=['GET', 'POST'])
def show_glyph(glyph_id):
    """Show details of glyph (if it exists) or redirect home."""

    glyph_list = Glyph.query.filter(Glyph.id == glyph_id).all()

    if len(glyph_list) == 0:
        return redirect(url_for('public.home'))
    else:
        return render_template('glyph/view.html', glyph=glyph_list[0])


@blueprint.route('/<glyph_id>/comment', methods=['GET', 'POST'])
@login_required
def glyph_comment(glyph_id):
    """Comment on a glyph."""

    form = CommentForm(request.form)
    if form.validate_on_submit() and request.method == 'POST':
        comment = Comment.create(name=form.name.data, rating=form.rating.data, comment=form.comment.data,
                                 user_id=current_user.id, glyph_id=glyph_id)

        # ensure all comments from same user give same rating
        for c in Comment.query.filter(Comment.user_id==current_user.id, Comment.glyph_id==comment.glyph_id).all():
            c.rating = form.rating.data
            c.save()

        flash('Comment successfully updated.', 'success')
        return redirect(url_for('glyph.show_glyph', glyph_id=glyph_id))
    else:
        flash_errors(form)

    return render_template('comment/add-comment.html', form=form)


@blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_glyph():
    """Add new glyph."""

    form = AddGlyphForm(request.form)

    options = map(lambda term: (str(term.id), term.name + " (" + term.get_full_id() + ")"), SOterm.query.all())
    options.append(("", ""))
    form.soTerm.choices = options

    if form.validate_on_submit() and request.method == 'POST':

        new_glyph = Glyph.create(name=form.name.data, file_name='', soterm_id=form.soTerm.data,
                                 user_id=current_user.id, proposal_url=form.proposal_url.data,
                                 sbol_status=form.sbol_status.data)

        valid_file = False
        for i in range(1, 5):
            file_added = new_glyph.save_glyph_file(request.files["file_path" + str(i)])
            valid_file = (valid_file or file_added)

        if not valid_file:
            new_glyph.delete()
            flash('No file found.', 'warning')
            return redirect(url_for('glyph.home'))

        for i in range(1, 5):
            new_glyph.save_specification_file(request.files["file_spec_path" + str(i)])

        flash('Glyph successfully added.', 'success')
        return redirect(url_for('glyph.show_glyph', glyph_id=new_glyph.id))

    else:
        flash_errors(form)

    return render_template('glyph/add-glyph.html', form=form)


@blueprint.route('/<glyph_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_glyph(glyph_id):
    """Edit glyph."""

    glyph = Glyph.query.filter(Glyph.id == glyph_id).first()

    if current_user != glyph.user and not current_user.is_admin:
        flash('Cannot edit - not your glyph!.', 'warning')
        return redirect(url_for('glyph.show_glyph', glyph_id=glyph_id))

    form = AddGlyphForm(request.form, name=glyph.name, soTerm=glyph.soterm, sbol_status=glyph.sbol_status, proposal_url=glyph.proposal_url)

    options = map(lambda term: (str(term.id), term.name + " (" + term.get_full_id() + ")"), SOterm.query.all())
    options.append(("", ""))
    form.soTerm.choices = options

    if form.validate_on_submit() and request.method == 'POST':

        glyph.update(name=form.name.data, soterm_id=form.soTerm.data, proposal_url=form.proposal_url.data,
                     sbol_status=form.sbol_status.data)

        for i in range(1, 5):
            glyph.save_glyph_file(request.files["file_path" + str(i)])

        for i in range(1, 5):
            glyph.save_specification_file(request.files["file_spec_path" + str(i)])

        glyph.save()

        flash('Glyph successfully updated.', 'success')
        return redirect(url_for('glyph.show_glyph', glyph_id=glyph_id))

    else:
        flash_errors(form)

    return render_template('glyph/edit-glyph.html', form=form, glyph=glyph)

glyphrepository/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from glyphrepository.user.models import User
from glyphrepository.glyph.models import Glyph

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """If no user specified, redirect to homepage."""
    return redirect(url_for('public.home'))


@blueprint.route('/<user_id>')
def user(user_id):
    """Show all Glyphs by a single user."""

    user = User.query.filter(User.id == user_id).all()[0]
    glyphs = Glyph.query.filter(Glyph.user_id == user_id).order_by(Glyph.soterm_id.asc()).all()

    return render_template('user/user.html', user=user, glyphs=glyphs)

glyphrepository/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

glyphrepository/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>Created by James Scott-Brown, Margarita Kopniczky and Iulia Gherman during the BDAthlon at
        <a href="http://www.iwbdaconf.org/2017/">IWBDA 2017</a>. </li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:james@jamesscottbrown.com">Contact</a></li>
    </ul>
  </small>
</footer>

glyphrepository/templates/glyph-table.html
<div id="glyph-table">
    <input type="text" id="myInput" class="form-control, input-lg" onkeyup="search_glyph_table()"
           placeholder="Filter by SO term...">
    <div id="glyph-table-inner" class="pre-scrollable" style="max-height: none;">
        <table id="myTable" class='table'>
            <tr class="header">
                <th style="width:10%;">Icon</th>
                <th style="width:30%;">Name</th>
                <th style="width:30%;"><abbr title="Glyphs begin as 'Proposed', are 'Endorsed' once they are recommended for use, and are 'Adopted' when they become part of the official standard">SBOL Status</abbr></th>
                <th style="width:30%;"><a href="http://www.sequenceontology.org/">SO Terms</a></th>
                <th style="width:30%;">Average Rating</th>
                <th style="width:30%;"><abbr title="Note that this may not be the original creator">Uploaded by</abbr></th>
            </tr>
            <tbody>
            {% for glyph in glyphs %}
                <tr>
                    <td class="col-sm-1"><div class="icon-container"><a href="/glyph/{{ glyph.id }}"><img src= "static/glyphs/{{ glyph.get_preferred_filename() }}" alt="{{ glyph.name }}"></a></div>
                    </th>
                    <td class="col-sm-2"> <a href="/glyph/{{ glyph.id }}">{{ glyph.name }}</a> </td>
                    <td class="col-sm-2"> {{ glyph.sbol_status }} </td>
                    <td class="col-sm-2"> {{ glyph.get_soterm_link() | safe }}</td>
                    <td class="col-sm-2"> {{ glyph.average_rating() }} </td>
                    <td class="col-sm-2"> <a href="/users/{{ glyph.user.id }}">{{ glyph.user.username }}</a> </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

glyphrepository/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    SynBio Glyphs
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}" {% block body_other %}{% endblock %}>
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

glyphrepository/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      SynBio Glyphs

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.about') }}">About</a></li>
      <li><a href="{{ url_for('glyph.add_glyph') }}">Add glyph</a></li>
              <li><a href="https://github.com/BDAthlon/2017-Triple_Helix-1"><i class="fa fa-github-alt" aria-hidden="true"></i></a></li>



    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% else %}

    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
      <li><a href="{{ url_for('public.login') }}">Log in</a></li>
      <li><a href="/github-login">login via GitHub</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
    </ul>

    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>